from django.contrib import admin
from models import Framework,FrameworkList,ProblemTagList,Problem,Menu,MenuList,Sequences,Theme,ThemeList,Tag,TagList,Note,Idea,IdeaList,Todo,TodoList,Link,LinkList,Statistic,Project,SourceCodeFile,ChartStyleList,ChartThemeList,PriorityList,InputFile,OutputFile,InputGeneratorFile,TimelineList

admin.site.register(Framework)
admin.site.register(Menu)
admin.site.register(MenuList)
admin.site.register(FrameworkList)
admin.site.register(ProblemTagList)
admin.site.register(Problem)
admin.site.register(Sequences)
admin.site.register(Theme)
admin.site.register(ThemeList)
admin.site.register(Tag)
admin.site.register(TagList)
admin.site.register(Note)
admin.site.register(Idea)
admin.site.register(IdeaList)
admin.site.register(Todo)
admin.site.register(TodoList)
admin.site.register(LinkList)
admin.site.register(Link)
admin.site.register(Statistic)
admin.site.register(Project)
admin.site.register(SourceCodeFile)
admin.site.register(InputGeneratorFile)
admin.site.register(InputFile)
admin.site.register(OutputFile)
admin.site.register(ChartStyleList)
admin.site.register(ChartThemeList)
admin.site.register(PriorityList)
admin.site.register(TimelineList)